# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Boun Comp Ling
description: >- # this means to ignore newlines until "baseurl:"
  This webpage is a mainhub for the computational linguistics reading group in Bogazici University, Linguistics Department.
baseurl: "" # the subpath of the site
url: "https://bouncompling.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: #"UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Team
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email Group
      value: boun_comp_ling@googlegroups.com
      link: mailto:boun_comp_ling@googlegroups.com
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    # - name: LinkedIn
    #   link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/BounCompLing
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
